# Generated by Django 6.0.2 on 2026-04-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('skill', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('learner', 'Learner')], max_length=10)),
            ],
        ),
    ]
