# Generated by Django 6.0.2 on 2026-05-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
