# Generated by Django 6.0.2 on 2026-05-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_rename_timestamp_message_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
