# Generated by Django 6.0.2 on 2026-05-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0014_rename_created_at_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
