# Generated by Django 6.0.2 on 2026-05-23 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0017_message_file_message_voice_alter_message_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='chat_voice/'),
        ),
    ]
