# Generated by Django 6.0.2 on 2026-05-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0018_message_image_alter_emailotp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.AlterField(
            model_name='message',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
    ]
