# Generated by Django 6.0.2 on 2026-05-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0019_remove_message_image_alter_message_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
